# Generated by Django 5.0.2 on 2024-03-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_quiz_alter_payment_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quiz',
            name='serial_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='week_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='week_id',
            field=models.IntegerField(default=0),
        ),
    ]
